//Countries cannot amend support or switch product
export const nonServiceableCountries: string[] = [
	'Aland Islands',
	'Albania',
	'Algeria',
	'American Samoa',
	'Andorra',
	'Angola',
	'Anguilla',
	'Antarctica',
	'Antigua And Barbuda',
	'Argentina',
	'Armenia',
	'Aruba',
	'Azerbaijan',
	'Bahamas',
	'Bahrain',
	'Bangladesh',
	'Barbados',
	'Belize',
	'Benin',
	'Bermuda',
	'Bhutan',
	'Bolivia',
	'Bonaire, Saint Eustatius and Saba',
	'Botswana',
	'Bouvet Island',
	'British Indian Ocean Territory',
	'Brunei Darussalam',
	'Burkina Faso',
	'Cambodia',
	'Cameroon',
	'Cape Verde',
	'Cayman Islands',
	'Chad',
	'Chile',
	'China',
	'Christmas Island',
	'Cocos (Keeling) Islands',
	'Colombia',
	'Comoros',
	'Congo',
	'Congo, the Democratic Republic of the',
	'Cook Islands',
	'Costa Rica',
	"Cote d'Ivoire",
	'Curacao',
	'Djibouti',
	'Dominica',
	'Dominican Republic',
	'Ecuador',
	'Egypt',
	'El Salvador',
	'Equatorial Guinea',
	'Eritrea',
	'Ethiopia',
	'Faroe Islands',
	'Fiji',
	'French Guiana',
	'French Polynesia',
	'French Southern Territories',
	'Gabon',
	'Gambia',
	'Georgia',
	'Ghana',
	'Greenland',
	'Grenada',
	'Guadeloupe',
	'Guam',
	'Guatemala',
	'Guyana',
	'Heard Island and McDonald Islands',
	'Holy See (Vatican City State)',
	'Honduras',
	'Indonesia',
	'Jamaica',
	'Jordan',
	'Kazakhstan',
	'Kenya',
	'Kiribati',
	'Korea, Republic of',
	'Kuwait',
	'Kyrgyzstan',
	"Lao People's Democratic Republic",
	'Lesotho',
	'Liberia',
	'Liechtenstein',
	'Macao',
	'Macedonia, the former Yugoslav Republic of',
	'Madagascar',
	'Malawi',
	'Maldives',
	'Marshall Islands',
	'Martinique',
	'Mauritania',
	'Mauritius',
	'Mayotte',
	'Micronesia, Federated States of',
	'Moldova, Republic of',
	'Monaco',
	'Mongolia',
	'Montenegro',
	'Montserrat',
	'Morocco',
	'Mozambique',
	'Namibia',
	'Nauru',
	'Nepal',
	'New Caledonia',
	'Niger',
	'Nigeria',
	'Niue',
	'Norfolk Island',
	'Northern Mariana Islands',
	'Oman',
	'Pakistan',
	'Palau',
	'Panama',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Philippines',
	'Pitcairn',
	'Puerto Rico',
	'Qatar',
	'Reunion',
	'Rwanda',
	'Saint Barthelemy',
	'Saint Helena',
	'Saint Kitts and Nevis',
	'Saint Lucia',
	'Saint Martin (French part)',
	'Saint Pierre and Miquelon',
	'Saint Vincent and the Grenadines',
	'Samoa',
	'San Marino',
	'Sao Tome and Principe',
	'Saudi Arabia',
	'Senegal',
	'Serbia',
	'Seychelles',
	'Sierra Leone',
	'Sint Maarten',
	'Solomon Islands',
	'South Georgia and the South Sandwich Islands',
	'Sri Lanka',
	'Sudan',
	'Suriname',
	'Svalbard and Jan Mayen',
	'Swaziland',
	'Syrian Arab Republic',
	'Taiwan',
	'Tajikistan',
	'Tanzania, United Republic of',
	'Thailand',
	'Timor-Leste',
	'Togo',
	'Tokelau',
	'Tonga',
	'Trinidad and Tobago',
	'Tunisia',
	'Turkey',
	'Turkmenistan',
	'Turks and Caicos Islands',
	'Tuvalu',
	'Uganda',
	'Uruguay',
	'Uzbekistan',
	'Vanuatu',
	'Viet Nam',
	'Virgin Islands, British',
	'Wallis and Futuna',
	'Western Sahara',
	'Zambia',
];
