#!/bin/bash
shopt -s expand_aliases

set -e

# install node

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

nvm install
nvm use

# This could be removed if all TC agents guaranteed global yarn installed
PROJECT_ROOT=$(pwd)
alias yarn='node ${PROJECT_ROOT}/.yarn/releases/yarn-*.js'

(
  cd cdk
  yarn install --frozen-lockfile
  yarn lint
  yarn test
  yarn synth
)

# Installing packages via yarn

yarn install

# run tests with yarn

yarn test

# produce prod artifacts

yarn bundle

# push to riffraff

yarn node-riffraff-artifact
