#!/bin/bash
shopt -s expand_aliases

set -e

# cd into the app directory where package.json resides
cd app

# https://classic.yarnpkg.com/en/docs/cli/policies/#toc-policies-set-version
# This could be removed if all TC agents guaranteed   global yarn installed
alias yarn='node ../.yarn/releases/yarn-*.js'

# install node

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

nvm install
nvm use


# Installing packages via yarn

yarn install

# run tests with yarn

yarn test

# produce prod artifacts

yarn bundle

# push to riffraff

export TEAMCITY_BRANCH=${TEAMCITY_BRANCH/\/merge/PR merge} # workaround for .split("/").slice(-1)[0] in 'node-riffraff-artefact'

yarn riffraff