#!/bin/bash

set -e

# Installing yarn
YARN_VERSION="1.6.0"
YARN_LOCATION="$(pwd)/tools/${YARN_VERSION}"

if [ ! -d "$YARN_LOCATION" ]; then
	mkdir -p ${YARN_LOCATION}
	cd ${YARN_LOCATION}/
	wget -qO- https://github.com/yarnpkg/yarn/releases/download/v${YARN_VERSION}/yarn-v${YARN_VERSION}.tar.gz | tar zvx
	cd ../..
fi

YARN_EXEC=${YARN_LOCATION}/yarn-v$YARN_VERSION/bin/yarn

# cd into the app directory where package.json resides

cd app

# install node

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

nvm install
nvm use

# Installing packages via yarn

${YARN_EXEC} install

# run tests with yarn

${YARN_EXEC} test

# produce prod artifacts

${YARN_EXEC} bundle