export const mockRecords = [
  {
    deliveryDate: "2019-12-05",
    deliveryInstruction: "Description",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-12-04",
    deliveryInstruction: "Description",
    hasHolidayStop: true
  },
  {
    deliveryDate: "2019-12-03",
    deliveryInstruction: "Description",
    deliveryAddress: "Different Address, Line 2, London, UK, E1 2QA",
    addressLine1: "Different Address",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E2 3WB",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-12-02",
    deliveryInstruction: "Description",
    deliveryAddress: "Different Address, Line 2, London, UK, E1 2QA",
    addressLine1: "Different Address",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E2 3WB",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-12-01",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-30",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-28",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  },
  {
    deliveryDate: "2019-11-29",
    deliveryInstruction: "Description",
    deliveryAddress: "Main St, Line 2, London, UK, E1 2QA",
    addressLine1: "Main St",
    addressLine2: "Line 2",
    addressTown: "London",
    addressCountry: "UK",
    addressPostcode: "E1 2QA",
    hasHolidayStop: false
  }
];
