name: manage-frontend cypress (mocked)
on:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  cypress:
    name: Manage-frontend Cypress (mocked)
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5, 6]

    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.MANAGE_FRONTEND_IAM_ROLE }}
          aws-region: eu-west-1

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn cypress:mocked:server
          wait-on: 'http://localhost:9234, http://localhost:9233'
          wait-on-timeout: 30
          quiet: true
          browser: chrome
          spec: cypress/tests/mocked/parallel-${{ matrix.group }}/*.cy.ts
          config: baseUrl=http://localhost:9234
